### ISSUE TITLE
Not named "FTBrony" anymore

### ISSUE THREAD

**Issue by EpicLPer** [mtheall/ftpd#33]
Very, VERY big issue. Totally not kidding.

You really gave the haters this point?

**Comment by Michpem** [comment]
If anything it's because the app became very popular as of late, probably because of the new Homebrew exploits and the fact that it's the only good FTP app that is updated constantly, and, you know, not everyone likes MLP, so having a more "neutral" look is a welcome change, yet that doesn't make anyone a hater. For me it really didn't matter because I can just edit the source code to replace that stuff with something of my liking anyway.

**Comment by EpicLPer** [comment]
Yeah, there were like 3 versions which only removed the picture and references to MLP already anways so where's the point in renaming this here.

**Comment by Michpem** [comment]
I can't talk for mtheall, but it's what makes the most sense to me; if the app is getting released with way more people in mind than before, then might as well make it more neutral. Also, most of the edits are older versions of the app, so now people can update to the newest version without having to ask someone else to edit all that stuff out.

**Comment by mtheall** [comment]
Here's the backstory:

When 3DS homebrew was first flourishing, smea asked if someone could make an FTP server, but then nobody did. So he made ftPONY (because someone asked him to put ponies in it?). Obviously that was sufficient for him because it worked in his workflow. Of course, I like to troll smea, so ftBRONY was born. I only had the idea because I had recently watched a documentary about bronies. Truth be told, I still don't know the name of the pony that was the bottom splash screen for so long. It grew to great popularity and many forks were made to replace the brony-branding with "family-appropriate" graphics. I don't know what was inappropriate in the first place. But anyways, the troll is over and this software (formerly known as ftbrony) has a mature code base which calls for a degree of professionalism. Obviously 99% of my users are gbatemp members so they wouldn't get it. Besides, if someone else named their 3DS FTP server ftpd, I could no longer claim to be the de-facto standard. You can always fork this project and brand it to your liking; I contributed it as public domain so that anyone can do what they wish with it.

With that said, I will now sit back and watch the brony flame-wars commence.

**Comment by ErmanSayin** [comment]
normal people don't want to have their parents think they're degenerates
