### ISSUE TITLE
Recieveing a spotpass item breaks ftpd

### ISSUE THREAD

**Issue by ghost** [mtheall/ftpd#44]
Recieveing any spotpass item breaks ftpd, and causes repeated spam of error 22 until you close the app.

**Comment by mtheall** [comment]
Can you give a specific error message? Does it say which function failed?

**Comment by fox8091** [comment]
It says getting socExit() fails. I assume this is because the spotpass notification triggered right as I closed the 3DS, interrupting the normal socExit function.

**Comment by Amzamiviram** [comment]
Im also having this problem, right after I enabled spotpass on fire emblem. I use windows explorer as my client and it says that the server is ready only because the proxy server is not set up to allow full access. On the 3ds it says
accepted connection from 192.168.1.4:5504
220 Hello!
User Anonymous
230 OK
SYST
215 UNIX Type: L8
PWD
257"/"
TYPE I
200 OK
PASV
binding to 192.168.1.5:5002
listening on 192.168.1.5:5002
227 192,168,1,5,19,138
LIST -l
stop listening on 192.168.1.5:5002
550 No such file or directory
QUIT
221 disconnecting
closing connection to 192.168.1.4:55047

**Comment by mtheall** [comment]
I'm not sure this is something we know how to avoid.
