### ISSUE TITLE
not working when internet is down...

### ISSUE THREAD

**Issue by lomejor18** [mtheall/ftpd#61]
why FTDP doesn't work when there's no internet but the router wifi works fine... i mean, both 3ds and PC still are conected in the local network...
thanks...

**Comment by mtheall** [comment]
This is a limitation of homebrew. See https://github.com/Lectem/FakeMii

**Comment by DumbJoe** [comment]
What are you talking about? I turned off the modem or at least unplugged the DSL cable and tried to connect to my 3DS FTP server with FileZilla and it works! So unless the author has already incorporated this FakeMii into he's ftpd app but hasn't mentioned so yet, then your issue is probably due from flaky connections or bugginess of the ftpd program itself....
