### ISSUE TITLE
Command support for Chrome and similar

### ISSUE THREAD

**Issue by Techy4198** [mtheall/ftpd#64]
Using Chrome browser as client, the following commands are sent giving the errors;
`SIZE /` -> 550 Could not get file size.
`LIST -l` -> 550 No such file or directory
Only a minor issue, since there are other working clients.

**Comment by mtheall** [comment]
The `SIZE /` failure appears to be ignored by Chrome. I won't change anything for this because I'm fairly certain using the `SIZE` command on a directory is ill-defined, i.e. it only applies to files.

The `LIST -l` failure is a similar problem as `LIST -a`. While technically `LIST -a` can only mean "list the directory named '-a'", many clients use it to mean "list the current directory without excluding 'hidden' files". There is a workaround for that, and adding support for the `-l` variant should be trivial.

Please note that if you actually have a directory named `-a` or `-l` then that directory will be listed. Or if you did something like `LIST -a some/path` and a directory named "-a some/path" actually exists, it will be listed instead of "some/path".
